apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: kokafanta24/app-web:1e16393
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index/login_page.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /index/login_page.php
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /index/login_page.php
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "bd_final"
        - name: DB_USER
          value: "appuser"
        - name: DB_PASS
          value: "apppassword"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 80
